resource "echostream_message_type" "test" {
  auditor            = "def auditor(*, message, **kwargs):\n    print(\"foo\")\n    return {}\n"
  bitmapper_template = "def bitmapper(*, context, message, source, **kwargs):\n\n    from decimal import Decimal\n    import simplejson as json\n\n    message = json.loads(message, parse_float=Decimal)\n\n    bitmap = 0x0\n\n    # TODO - Perform conditional bitmapping of the JSON message here.\n    # The returned bitmap will be compared against the routes in the\n    # route table for route matching. This will be done by\n    # (message_bitmap \u0026 route) == route. If no routes match, the\n    # message will be filtered.\n\n    return bitmap\n"
  description        = "Test message type"
  name               = "test"
  processor_template = "def processor(*, context, message, source, **kwargs):\n\n    from decimal import Decimal\n    import simplejson as json\n\n    message = json.loads(message, parse_float=Decimal)\n\n    # TODO - Perform any transformations to the message here.\n    # This can include transforming the message to something that\n    # is no longer JSON. Remember, you MUST return a string or None.\n    # If None is returned, the message will be filtered.\n\n    return json.dumps(message, separators=(\",\", \":\"), use_decimal=True)\n"
  readme             = "# echo.json\n\nRepresents a [JavaScript Object Notation (JSON)](https://en.wikipedia.org/wiki/JSON) formatted message.\n\nJSON is extensively used to transport data, provide input and results from API's, and store data in many different databases. It is very software language friendly, with almost all modern languages supporting it inherently.\n\nAn example of JSON formatted data:\n```json\n{\n    \"firstName\": \"John\",\n    \"lastName\": \"Smith\",\n    \"isAlive\": true,\n    \"age\": 27,\n    \"address\": {\n    \"streetAddress\": \"21 2nd Street\",\n    \"city\": \"New York\",\n    \"state\": \"NY\",\n    \"postalCode\": \"10021-3100\"\n    },\n    \"phoneNumbers\": [\n        {\n            \"type\": \"home\",\n            \"number\": \"212 555-1234\"\n        },\n        {\n            \"type\": \"office\",\n            \"number\": \"646 555-4567\"\n        }\n    ],\n    \"children\": [],\n    \"spouse\": null\n}\n```\n\nThe only requirement for this message type is correctly formatted JSON."
  sample_message     = "{\n  \"firstName\": \"John\",\n  \"lastName\": \"Smith\",\n  \"isAlive\": true,\n  \"age\": 27,\n  \"address\": {\n    \"streetAddress\": \"21 2nd Street\",\n    \"city\": \"New York\",\n    \"state\": \"NY\",\n    \"postalCode\": \"10021-3100\"\n  },\n  \"phoneNumbers\": [\n    {\n      \"type\": \"home\",\n      \"number\": \"212 555-1234\"\n    },\n    {\n      \"type\": \"office\",\n      \"number\": \"646 555-4567\"\n    }\n  ],\n  \"children\": [],\n  \"spouse\": null\n}"
}
